version: '3'
services:
  web:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /home/node/frontend/node_modules
      - .:/home/node/frontend
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /home/node/frontend/node_modules
      - .:/home/node/frontend
    command: ['npm', 'run', 'test']